env:
  node: true
  mocha: true
extends:
  - 'eslint-config-airbnb-base'
rules:
  no-underscore-dangle:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoid-escape
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  operator-linebreak:
    - off
